name:                rssify
version:             0.1.0.0
github:              "ostnam/rssify"
license:             BSD3
author:              "ostnam"
maintainer:          "tsougaevm@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ostnam/rssify#readme>

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.12 && < 1
- tagsoup >= 0.14 && < 1
- feed >= 1.3 && < 2
- text >= 1 && < 2
- wreq >= 0.5 && < 1
- lens >= 5 && < 6
- bytestring >= 0.11 && < 1
- stm >= 2 && < 3
- aeson >= 2 && < 3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rssify-example:
    source-dirs: examples
    main: Example.hs
    dependencies: rssify
